invenio_comments/views.py
# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2012, 2013, 2014, 2015 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

"""WebSearch Flask Blueprint."""

import socket
from datetime import datetime

from flask import Blueprint, abort, current_app, flash, g, redirect, \
    render_template, request, url_for
from flask_breadcrumbs import register_breadcrumb
from flask_login import current_user, login_required
from flask_menu import register_menu

from invenio_base.decorators import templated
from invenio_base.globals import cfg
from invenio_base.i18n import _
from invenio_ext.principal import permission_required
from invenio_ext.sqlalchemy import db
from invenio_utils.mail import email_quote_txt
from invenio_records.utils import visible_collection_tabs
from invenio_records.views import request_record

from .forms import AddCmtRECORDCOMMENTForm, AddCmtRECORDCOMMENTFormReview
from .models import CmtACTIONHISTORY, CmtRECORDCOMMENT, CmtSUBSCRIPTION
from .utils import comments_nb_counts, reviews_nb_counts

CFG_SITE_RECORD = 'record'

blueprint = Blueprint('comments', __name__, url_prefix="/" + CFG_SITE_RECORD,
                      template_folder='templates', static_folder='static')


def log_comment_action(action_code, id, recid, uid=None):
    action = CmtACTIONHISTORY(
        id_cmtRECORDCOMMENT=id,
        id_bibrec=recid,
        id_user=uid or current_user.get_id(),
        client_host=int(socket.inet_aton(request.remote_addr).encode('hex'),
                        16),
        action_time=datetime.now(),
        action_code=action_code)
    db.session.add(action)
    db.session.commit()


class CommentRights(object):

    def __init__(self, comment, uid=None):
        self.id = comment
        self.uid = uid or current_user.get_id()
        self.id_collection = 0  # FIXME

    def authorize_action(self, *args, **kwargs):
        from invenio_access.engine import acc_authorize_action
        return acc_authorize_action(*args, **kwargs)

    def can_perform_action(self, action=None):
        cond = CmtACTIONHISTORY.id_user == self.uid \
            if self.uid > 0 else \
            CmtACTIONHISTORY.client_host == \
            socket.inet_aton(request.remote_addr)

        if action in cfg['CFG_WEBCOMMENT_ACTION_CODE']:
            cond = db.and_(cond, CmtACTIONHISTORY.action_code ==
                           cfg['CFG_WEBCOMMENT_ACTION_CODE'][action])

        return CmtACTIONHISTORY.query.filter(
            CmtACTIONHISTORY.id_cmtRECORDCOMMENT == self.id, cond).\
            count() == 0

    def can_view_restricted_comment(self, restriction):
        # restriction =  self.comment.restriction
        if restriction == "":
            return (0, '')
        return self.authorize_action(
            self.uid,
            'viewrestrcomment',
            status=restriction)

    def can_send_comment(self):
        return self.authorize_action(
            self.uid,
            'sendcomment',
            authorized_if_no_roles=True,
            collection=self.id_collection)

    def can_attach_comment_file(self):
        return self.authorize_action(
            self.uid,
            'attachcommentfile',
            authorized_if_no_roles=False,
            collection=self.id__collection)


@blueprint.route('/<int:recid>/comments/add', methods=['GET', 'POST'])
@request_record
@login_required
@permission_required('sendcomment', authorized_if_no_roles=True,
                     collection=lambda: g.collection.id)
def add_comment(recid):
    uid = current_user.get_id()
    in_reply = request.args.get('in_reply', type=int)
    if in_reply is not None:
        comment = CmtRECORDCOMMENT.query.get(in_reply)

        if comment.id_bibrec != recid or comment.is_deleted:
            abort(401)

        if comment is not None:
            c = CmtRECORDCOMMENT()
            c.title = _('Re: ') + comment.title
            c.body = email_quote_txt(comment.body or '')
            c.in_reply_to_id_cmtRECORDCOMMENT = in_reply
            form = AddCmtRECORDCOMMENTForm(request.form, obj=c)
            return render_template('comments/add.html', form=form)

    form = AddCmtRECORDCOMMENTForm(request.values)
    if form.validate_on_submit():
        c = CmtRECORDCOMMENT()
        form.populate_obj(c)
        c.id_bibrec = recid
        c.id_user = uid
        c.date_creation = datetime.now()
        c.star_score = 0
        try:
            db.session.add(c)
            db.session.commit()
            flash(_('Comment was sent'), "info")
            from urlparse import urlparse
            if 'notes' in urlparse(request.referrer).path:
                return redirect(url_for('comments.notes', recid=recid) +
                                '#' + form.pdf_page.data)
            return redirect(url_for('comments.comments', recid=recid))
        except:
            db.session.rollback()

    return render_template('comments/add.html', form=form)


@blueprint.route('/<int:recid>/reviews/add', methods=['GET', 'POST'])
@request_record
@login_required
@permission_required('sendcomment', authorized_if_no_roles=True,
                     collection=lambda: g.collection.id)
def add_review(recid):
    uid = current_user.get_id()
    form = AddCmtRECORDCOMMENTFormReview(request.values)
    if form.validate_on_submit():
        c = CmtRECORDCOMMENT()
        form.populate_obj(c)
        c.id_bibrec = recid
        c.id_user = uid
        c.date_creation = datetime.now()
        try:
            db.session.add(c)
            db.session.commit()
            flash(_('Review was sent'), "info")
            return redirect(url_for('comments.reviews', recid=recid))
        except:
            db.session.rollback()

    return render_template('comments/add_review.html', form=form)


@blueprint.route('/<int:recid>/comments', methods=['GET', 'POST'])
@request_record
@register_menu(blueprint, 'record.comments', _('Comments'), order=5,
               visible_when=visible_collection_tabs('comments'),
               endpoint_arguments_constructor=lambda:
               dict(recid=request.view_args.get('recid')),
               count=comments_nb_counts)
def comments(recid):
    """Display comments."""
    from invenio_access.local_config import VIEWRESTRCOLL
    from invenio_access.mailcookie import \
        mail_cookie_create_authorize_action
    from .api import check_user_can_view_comments
    auth_code, auth_msg = check_user_can_view_comments(current_user, recid)
    if auth_code and current_user.is_guest:
        cookie = mail_cookie_create_authorize_action(VIEWRESTRCOLL, {
            'collection': g.collection})
        url_args = {'action': cookie, 'ln': g.ln, 'referer': request.referrer}
        flash(_("Authorization failure"), 'error')
        return redirect(url_for('webaccount.login', **url_args))
    elif auth_code:
        flash(auth_msg, 'error')
        abort(401)

    # FIXME check restricted discussion
    comments = CmtRECORDCOMMENT.query.filter(db.and_(
        CmtRECORDCOMMENT.id_bibrec == recid,
        CmtRECORDCOMMENT.in_reply_to_id_cmtRECORDCOMMENT == 0,
        CmtRECORDCOMMENT.star_score == 0
    )).order_by(CmtRECORDCOMMENT.date_creation).all()
    return render_template('comments/comments.html', comments=comments,
                           option='comments')


@blueprint.route('/<int:recid>/reviews', methods=['GET', 'POST'])
@request_record
@register_menu(blueprint, 'record.reviews', _('Reviews'), order=6,
               visible_when=visible_collection_tabs('reviews'),
               endpoint_arguments_constructor=lambda:
               dict(recid=request.view_args.get('recid')),
               count=reviews_nb_counts)
def reviews(recid):
    """Display reviews."""
    from invenio_access.local_config import VIEWRESTRCOLL
    from invenio_access.mailcookie import \
        mail_cookie_create_authorize_action
    from .api import check_user_can_view_comments
    auth_code, auth_msg = check_user_can_view_comments(current_user, recid)
    if auth_code and current_user.is_guest:
        cookie = mail_cookie_create_authorize_action(VIEWRESTRCOLL, {
            'collection': g.collection})
        url_args = {'action': cookie, 'ln': g.ln, 'referer': request.referrer}
        flash(_("Authorization failure"), 'error')
        return redirect(url_for('webaccount.login', **url_args))
    elif auth_code:
        flash(auth_msg, 'error')
        abort(401)

    comments = CmtRECORDCOMMENT.query.filter(db.and_(
        CmtRECORDCOMMENT.id_bibrec == recid,
        CmtRECORDCOMMENT.in_reply_to_id_cmtRECORDCOMMENT == 0,
        CmtRECORDCOMMENT.star_score > 0
    )).order_by(CmtRECORDCOMMENT.date_creation).all()
    return render_template('comments/reviews.html', comments=comments)


@blueprint.route('/<int:recid>/report/<int:id>', methods=['GET', 'POST'])
@login_required
@request_record
def report(recid, id):
    if CommentRights(id).can_perform_action():
        CmtRECORDCOMMENT.query.filter(CmtRECORDCOMMENT.id == id).update(dict(
            nb_abuse_reports=CmtRECORDCOMMENT.nb_abuse_reports + 1),
            synchronize_session='fetch')

        log_comment_action(cfg['CFG_WEBCOMMENT_ACTION_CODE']['REPORT_ABUSE'],
                           id, recid)
        flash(_('Comment has been reported.'), 'success')
    else:

invenio_comments/templates/comments/add.html
{#
# This file is part of Invenio.
# Copyright (C) 2014 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{%- extends "comments/add_base.html" -%}

invenio_comments/templates/comments/add_base.html
{#
# This file is part of Invenio.
# Copyright (C) 2012, 2013, 2014, 2015 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{% from "_formhelpers.html" import render_field with context %}
{% macro add_comment() %}
<form name="write_message"
      action="{{ url_for('comments.add_comment', recid=recid) }}"
      style="{{ 'margin-bottom:0px;' if request.is_xhr }}"
      method="post" class="form-horizontal"
      onsubmit="COMMENTS.formSubmitActions();">
  <div class="{{ 'modal-body' if request.is_xhr }}">
      {{ form.csrf_token }}
      {{ render_field(form.in_reply_to_id_cmtRECORDCOMMENT) }}
      {{ render_field(form.title) }}
      {{ render_field(form.body,
                      rows="15",
                      autofocus=true,
                      id="comment-textarea",
                      title=_("Annotations Help"),
                      popover_content=form.notes_howto if config.ANNOTATIONS_NOTES_ENABLED else '') }}
      {{ render_field(form.pdf_page) }}
  </div>
  <div class="{{ 'modal-footer ' if request.is_xhr else 'form-actions'}}">
        <input type="submit" name="send_button" value="{{ _("Send") }}" class="btn btn-primary"/>
        {%- if request.is_xhr -%}
          <a class="btn btn-default" data-dismiss="modal">Close</a>
        {%- endif -%}
  </div>
</form>
{% endmacro %}

{%- if not request.is_xhr -%}
  {% extends "records/base.html" %}
  {%- if config.ANNOTATIONS_NOTES_ENABLED -%}
    {% bundle "comments.js" %}
  {%- endif -%}
  {% block record_content %}
  {{ add_comment() }}
  {% endblock %}
{%- else -%}

<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&times;</a>
      <h3>{{ _('Write a comment') }}</h3>
    </div>
    {{ add_comment() }}
  </div>
</div>
{%- endif -%}

invenio_comments/templates/comments/add_review.html
{#
# This file is part of Invenio.
# Copyright (C) 2014 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{%- extends "comments/add_review_base.html" -%}

invenio_comments/templates/comments/add_review_base.html
{#
# This file is part of Invenio.
# Copyright (C) 2012, 2013, 2014, 2015 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{% from "_formhelpers.html" import render_field with context %}
{% macro add_comment() %}
<form name="write_message"
      action="{{ url_for('comments.add_review', recid=recid) }}"
      style="{{ 'margin-bottom:0px;' if request.is_xhr }}"
      method="post" class="form-horizontal">
  <div class="{{ 'modal-body' if request.is_xhr }}">
    <div class="col-sd-12 col-xs-12">
      {{ form.csrf_token }}
      {{ render_field(form.in_reply_to_id_cmtRECORDCOMMENT) }}
      {{ render_field(form.title) }}
      {{ render_field(form.body) }}
      {{ render_field(form.star_score) }}
    </div>
  </div>
  <div class="{{ 'modal-footer ' if request.is_xhr else 'form-actions'}}">
        <input type="submit" name="send_button" value="{{ _("Send") }}" class="btn btn-primary"/>
        {%- if request.is_xhr -%}
          <a class="btn btn-default" data-dismiss="modal">Close</a>
        {%- endif -%}
  </div>
</form>
{% endmacro %}

{%- if not request.is_xhr -%}
  {% extends "records/base.html" %}
  {% block record_content %}
  {{ add_comment() }}
  {% endblock %}
{%- else -%}

<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&times;</a>
      <h3>{{ _('Write a review') }}</h3>
    </div>
    {{ add_comment() }}
  </div>
</div>
{%- endif -%}

invenio_comments/templates/comments/base.html
{#
# This file is part of Invenio.
# Copyright (C) 2014 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{%- extends "comments/base_base.html" -%}

invenio_comments/templates/comments/comments_base.html
{#
# This file is part of Invenio.
# Copyright (C) 2012, 2013, 2014, 2015 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{%- extends "comments/base.html" -%}
{%- from "previewer/pdf_base.html" import pdf_pane with context -%}

{%- if config.ANNOTATIONS_PREVIEW_ENABLED -%}
  {% bundles "previewer/pdftk.css", "previewer/pdftk.js"  %}
{%- endif -%}


{%- block custom -%}
  <div>
    {#{ pdf_pane() }#}
    <div {#{ 'class=col-md-6' if config.ANNOTATIONS_PREVIEW_ENABLED }#}>
      {%- if comments -%}
        <ul class="comments list-unstyled">
          {%- for c in comments recursive -%}
          <li name="{{ c.id }}">
            <a class="collapse-comment
              pull-left{{ ' collapsed' if c.is_collapsed(current_user.get_id()) }}"
             style="margin-right: 5px;"
             data-toggle="collapse"
             data-target="#collapse-{{ c.id }}">
            {%- if c.is_collapsed(current_user.get_id()) -%}
              <i class="glyphicon glyphicon-chevron-right">
            {%- else -%}
              <i class="glyphicon glyphicon-chevron-down">
            {%- endif -%}
              </i>
            </a>
            <h4>
            {{ c.title }}
            <small>
              {%- if c.nb_votes_total > 0 -%}
              {%- set votes = c.nb_votes_yes-(c.nb_votes_total-c.nb_votes_yes) -%}
              {%- if votes > 0 -%}
                /
                <span class="badge badge-success">
                +
                {{ votes }}
                </span>
              {%- elif votes < 0 -%}
                /
                <span class="badge badge-important">
                {{ votes }}
                </span>
              {%- endif -%}
              {%- endif -%}
              <a class="pull-right"
               title="{{ _('Permalink to this comment') }}"
               href="#{{ c.id }}">
              &para;
              </a>
              {%- if not c.title -%}
              &nbsp;
              {%- endif -%}
            </small>
            </h4>
            <div id="collapse-{{ c.id }}"
             data-action="{{ url_for('comments.toggle', recid=recid, id=c.id) }}"
             class="collapse{{ ' in' if not c.is_collapsed(current_user.get_id()) }}">
            <blockquote>
              <p style="font-size:90%;">
              {{ c.body|quoted_txt2html(
                indent_html=(
                  '<span style="border-left: 3px solid #CCC; padding-left:5px;">',
                  '</span>'))|safe }}
              </p>
              <small>
              {%- if c.user -%}
                <img src="{{ c.user.email|gravatar(size=14) }}"
                 alt="avatar"/>
                <a href="{{ url_for('webmessage.add', sent_to_user_nicks=c.user.nickname) }}">
                {{ c.user.nickname }}
                </a>
              {%- else -%}
                <img src="/img/user-icon-1-16x16.gif"
                 alt="avatar"/>
                {{ _('Guest') }}
              {%- endif -%}

              &nbsp;

              -
              <i class="icon-time"></i>
              {{ c.date_creation }}
              -
              <i class="glyphicon glyphicon-pencil"></i>
              {%- if current_user.is_guest -%}
                <a href="{{ url_for('webaccount.login', referer=url_for('comments.add_comment', recid=recid, in_reply=c.id)) }}">
              {%- else -%}
                <a data-toggle="modal"
                   data-target="#"
                   href="{{ url_for('comments.add_comment', recid=recid, in_reply=c.id) }}">
              {%- endif -%}
                  {{ _('reply') }}
                </a>
              -
              <i class="icon-question-sign"></i>
              {{ _('Was it helpful?') }}
              <a href="{{ url_for('comments.vote', recid=recid, id=c.id, value=1, referer=request.url) }}">
                <i class="icon-thumbs-up"></i>
                {{ _('yes') }}
              </a>
              /
              <a href="{{ url_for('comments.vote', recid=recid, id=c.id, value=-1, referer=request.url) }}">
                <i class="icon-thumbs-down"></i>
                {{ _('no') }}
              </a>
              -
              <a href="{{ url_for('comments.report', recid=recid, id=c.id) }}">
                <i class="icon-exclamation-sign"></i>
                {{ _('report abuse') }}
              </a>
              </small>
            </blockquote>

            {%- if c.replies -%}
              <ul class="list-unstyled" style="padding-left: 20px;">
                {{ loop(c.replies) }}
              </ul>
            {%- endif -%}
            </div>  <!-- /collapse -->

            {%- if not loop.last -%}
              <hr/>
            {%- endif -%}

          </li>
          {%- endfor -%}
        </ul>  <!-- /comments -->

        {{ super() }} {# bottom 'write' comment from base #}
      {%- else -%}
        <div class="alert alert-info">
          {{ _('There are no comments. Be the first commenting this record.') }}
        </div>
      {%- endif -%}
    </div>  <!-- /col-md-6 -->
  </div>  <!-- /row -->
{%- endblock custom -%}

invenio_comments/templates/comments/reviews_base.html
{#
# This file is part of Invenio.
# Copyright (C) 2012, 2013, 2014, 2015 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{%- if not request.is_xhr -%}
  {% extends "records/base.html" %}
{%- endif -%}

{% bundle "comments.js" %}

{% block record_content %}
  <div class="page-header">
    {{ format_record(record, 'hs', ln=g.ln)|safe }}
  </div>

  <div class="page-header">
    <h4>
      {{ _("Reviews") }}
      <small>
      {% if current_user.is_guest %}
        <a class="btn btn-default pull-right" href="{{ url_for('webaccount.login', referer=request.url) }}">
      {% else %}
        <a class="btn btn-default pull-right" data-toggle="modal" data-target="#" href="{{ url_for('comments.add_review', recid=recid) }}">
      {% endif %}
          <i class="glyphicon glyphicon-pencil"></i> {{ _('write review') }}
        </a>

      </small>
    </h4>
  </div>

  {%- if comments -%}

  <ul class="list-unstyled">
  {%- for c in comments -%}
  <li name="{{ c.id }}">
    <div>
    <h4>
    {{ c.title }}
    <small>
       /
      {{ ('<i class="glyphicon glyphicon-star"></i>'|safe) * (c.star_score) }}{{ ('<i class="glyphicon glyphicon-star-empty"></i>'|safe) * ((5-c.star_score)) }} &nbsp;
      {%- if c.nb_votes_total > 0 -%}
        {%- set votes = c.nb_votes_yes-(c.nb_votes_total-c.nb_votes_yes) -%}
        {%- if votes > 0 -%}
        / <span class="badge badge-success">+{{ votes }}</span>
        {%- elif votes < 0 -%}
        / <span class="badge badge-important">{{ votes }}</span>
        {%- endif -%}
      {%- endif -%}
      <a class="pull-right" title="{{ _('Permalink to this review') }}" href="#{{ c.id }}">&para;</a>
    </small>
    </h4>
    <blockquote>
      <p>
      {{ c.body }}
      </p>
      <small>

        {%- if c.user -%}
        <img src="{{ c.user.email|gravatar(size=14, default=url_for('static', filename='img/user-icon-1-16x16.gif', _external=True)) }}" alt="avatar"/>
        <a href="{{ url_for('webmessage.add', sent_to_user_nicks=c.user.nickname) }}">
          {{ c.user.nickname }}
        </a>
        {%- else -%}
        <img src="/img/user-icon-1-16x16.gif" alt="avatar"/>
          {{ _('Guest') }}
        {%- endif -%} &nbsp;
        - <i class="glyphicon glyphicon-time"></i> {{ c.date_creation }}
        - <i class="glyphicon glyphicon-question-sign"></i> {{ _('Was it helpful?') }}
          <a href="{{ url_for('comments.vote', recid=recid, id=c.id, value=1,
            referer=request.url
          ) }}">
          <i class="glyphicon glyphicon-thumbs-up"></i>
          {{ _('yes') }}
          </a> /
          <a href="{{ url_for('comments.vote', recid=recid, id=c.id, value=-1,
            referer=request.url
          ) }}">
          <i class="glyphicon glyphicon-thumbs-down"></i>
          {{ _('no') }}
          </a>
          -
          <a href="{{ url_for('comments.report', recid=recid, id=c.id,
            referer=request.url
          ) }}">
            <i class="glyphicon glyphicon-exclamation-sign"></i>
            {{ _('report abuse') }}
          </a>
      </small>
    </blockquote>
    </div>
  </li>
  {%- endfor -%}
  </ul>

  {% if current_user.is_guest %}
        <a class="btn btn-default pull-right" href="{{ url_for('webaccount.login', referer=request.url) }}">
          <i class="glyphicon glyphicon-pencil"></i> {{ _('write review') }}
        </a>
      {% else %}
        <a class="btn btn-default pull-right" data-toggle="modal" data-target="#" href="{{ url_for('comments.add_review', recid=recid) }}">
          <i class="glyphicon glyphicon-pencil"></i> {{ _('write review') }}
        </a>
      {% endif %}
  {%- else -%}
  <div class="alert alert-info">
    {{ _('There are no reviews. Be the first reviewing this record.') }}
  </div>
  {%- endif -%}

  <div style="clear:both"/></div>

{% endblock %}

{%- if request.is_xhr -%}
  <script type="text/javascript"> bindModals(null, 'input:text:visible:first'); </script>
{%- endif -%}